### ISSUE TITLE
ngnix

### ISSUE THREAD

**Issue by Andrian1994** [worksma/uni-gamecms#13]
Здраствуйте, я использованию hestiacp , как настроить nginx.conf не работает регистрация

```

#=========================================================================#
# Default Web Domain Template                                             #
# DO NOT MODIFY THIS FILE! CHANGES WILL BE LOST WHEN REBUILDING DOMAINS   #
# https://docs.hestiacp.com/admin_docs/web.html#how-do-web-templates-work #
#=========================================================================#

server {
    listen      51.195.144.68:80;
    server_name csf-team.ro www.csf-team.ro;
        
    include /home/admin/conf/web/csf-team.ro/nginx.forcessl.conf*;

    location / {
        proxy_pass      http://51.195.144.68:8080;
        location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|tif|tiff|css|js|htm|html|ttf|otf|webp|woff|txt|csv|rtf|doc|docx|xls|xlsx|ppt|pptx|odf|odp|ods|odt|pdf|psd|ai|eot|eps|ps|zip|tar|tgz|gz|rar|bz2|7z|aac|m4a|mp3|mp4|ogg|wav|wma|3gp|avi|flv|m4v|mkv|mov|mpeg|mpg|wmv|exe|iso|dmg|swf)$ {
            root           /home/admin/web/csf-team.ro/public_html;
            access_log     /var/log/apache2/domains/csf-team.ro.log combined;
            access_log     /var/log/apache2/domains/csf-team.ro.bytes bytes;
            expires        max;
            try_files      $uri @fallback;
        }
    }

    location /error/ {
        alias   /home/admin/web/csf-team.ro/document_errors/;
    }

    location @fallback {
        proxy_pass      http://51.195.144.68:8080;
    }

    location ~ /\.(?!well-known\/|file) {
       deny all; 
       return 404;
    }
	


    include /home/admin/conf/web/csf-team.ro/nginx.conf_*;
}
```

**Comment by worksma** [comment]
#=========================================================================#
# Default Web Domain Template                                             #
# DO NOT MODIFY THIS FILE! CHANGES WILL BE LOST WHEN REBUILDING DOMAINS   #
# https://docs.hestiacp.com/admin_docs/web.html#how-do-web-templates-work #
#=========================================================================#

server {
    listen      51.195.144.68:80;
    server_name csf-team.ro www.csf-team.ro;
        
    include /home/admin/conf/web/csf-team.ro/nginx.forcessl.conf*;

    location / {
        proxy_pass      http://51.195.144.68:8080;
        location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|tif|tiff|css|js|htm|html|ttf|otf|webp|woff|txt|csv|rtf|doc|docx|xls|xlsx|ppt|pptx|odf|odp|ods|odt|pdf|psd|ai|eot|eps|ps|zip|tar|tgz|gz|rar|bz2|7z|aac|m4a|mp3|mp4|ogg|wav|wma|3gp|avi|flv|m4v|mkv|mov|mpeg|mpg|wmv|exe|iso|dmg|swf)$ {
            root           /home/admin/web/csf-team.ro/public_html;
            access_log     /var/log/apache2/domains/csf-team.ro.log combined;
            access_log     /var/log/apache2/domains/csf-team.ro.bytes bytes;
            expires        max;
            try_files      $uri @fallback;
        }

        rewrite ^/(.*)$ /index.php?/$1 last;
    }

    location /error/ {
        alias   /home/admin/web/csf-team.ro/document_errors/;
    }

    location @fallback {
        proxy_pass      http://51.195.144.68:8080;
    }

    location ~ /\.(?!well-known\/|file) {
       deny all; 
       return 404;
    }
	


    include /home/admin/conf/web/csf-team.ro/nginx.conf_*;
}
