### ISSUE TITLE
Невозможно изменить cookie во время активного сеанса

### ISSUE THREAD

**Issue by Akllike** [worksma/uni-gamecms#14]
При установке сайта, после введенных всех необходимых данных, нажимая кнопку установить таблицы устанавливаются, но после этого вылетает ошибка 500 от php с жалобой на невозможность изменения cookie во время активного сеанса.

**PHP message: PHP Warning:  session_set_cookie_params(): Cannot change session cookie parameters when session is active in /var/www/stats/inc/classes/class.sessionscookies.php on line 23
PHP message: PHP Notice:  session_start(): A session had already been started - ignoring in /var/www/stats/inc/classes/class.sessionscookies.php on line 24
PHP message: PHP Parse error:  syntax error, unexpected 'endif' (T_ENDIF), expecting end of file in /var/www/stats/inc/classes/class.template.php(256) : eval()'d code on line 5'**

Ubuntu 18.04, Apache, php7.4, UNI GameCMS 5.7.7 Stable

**Comment by worksma** [comment]
Здравствуйте! Обратитесь пожалуйста на наш форум: https://forum.awscode.ru/index.php?forums/gamecms.14/
