### ISSUE TITLE
[Bug] Service -> Reload admins -> Null rcon-command

### ISSUE THREAD

**Issue by RockTheStreett** [worksma/uni-gamecms#2]
When working with services, an empty command is sent through rcon.
Tested: version 4.9.1, 4.9.3

P.S. The test was run both on a clean site (installed for the test) and on the prepared site.

**Comment by worksma** [comment]
[Исправлено в версии 5.0.8.5](https://github.com/worksma/uni-gamecms/commit/8238165584e6d1c330c429588f6c3a53bdf39593)
