### ISSUE TITLE
Не получается начать установку. Сразу после закидывания файлов на сервер и открытия сайта ошибка "Ошибка подключения к базе данных"

### ISSUE THREAD

**Issue by eugene-eliseev** [worksma/uni-gamecms#4]
Не получается начать установку. Сразу после закидывания файлов на сервер и открытия сайта ошибка "Ошибка подключения к базе данных"

Опытным путём выяснил, что виноват УЖЕ существующий файл /inc/configs/database.php
После его удаления установщик запускается как обычно, установка проходит успешно и проблем не возникает

Поправьте, чтобы в релиз этот файл не попадал (ну или нужны дополнительные проверки, что поля в этом конфиге не пустые)

**Comment by worksma** [comment]
Произвели удаление файла inc/configs/database.php в первоначальной версии.
https://github.com/worksma/uni-gamecms/commit/861ed90e1ba511e7f9bcce9295e18d1ed2847935
