### ISSUE TITLE
Платежная система

### ISSUE THREAD

**Issue by Dmitryyyyyyyy** [worksma/uni-gamecms#7]
Всем привет, у меня такая проблемма, когда пополняешь кошелек, оплата проходит на кассу, а вот на баланс сайта нет.

**Comment by worksma** [comment]
Проверьте валидность вводимых вами ключей, а также посмотрите логи платёжных систем в движке

**Comment by Dmitryyyyyyyy** [comment]
[AmaraPay] : [2022-01-19 15:23:49 | 193.124.200.243 | Неизвестный] : [Неизвестный ID пользователя]

**Comment by worksma** [comment]
На форуме была аналогичная проблема, человек просто указал вместо POST запросов GET.
Кассы в основном только с POST запросами работают

**Comment by Dmitryyyyyyyy** [comment]
На amarapay другой запрос и нельзя поставить, только post, на фрикассе тоже post стоит

**Comment by Dmitryyyyyyyy** [comment]
Проблемма решилась, шаблон купил кривой
