### ISSUE TITLE
Errors + English support maybe?

### ISSUE THREAD

**Issue by HowToRuski** [worksma/uni-gamecms#8]
Is there english support for this? It would be a nice feature to have, its pretty hard to translate from russian.

+ there is a lot of errors happening when i installed the site, i tried PHP 7.4 and PHP 8.1, both have same errors
https://i.imgur.com/8dfpoxR.png

**Comment by worksma** [comment]
English is not in demand among our audience, which, accordingly, indicates the meaninglessness of its support. To create a language system, we need a demanding audience to provide such services.
Stop using FastCGI and PHP-FPM. Demanding PHP version 7.4 (you can just CGI)

**Comment by HowToRuski** [comment]
I dont have FastCGI and PHP-FPM. 
FastCGI is no longer supported since PHP7.
PHP-FPM is only for linux users and i am on Windows.
